import DashboardLayout from "@/components/DashboardLayout";
import { Card, CardContent } from "@/components/ui/card";
import { useSheets } from "@/contexts/SheetsContext";
import { ExternalLink, MessageCircle, Phone, Search, UserRound, Copy, Send, Activity } from "lucide-react";
import { useMemo, useState } from "react";

type Row = Record<string, string>;
const LABELS: Record<string, string> = { lead_id: "معرف العميل", name: "الاسم", phone: "الهاتف", message: "الرسالة الأصلية", message_text: "نص الرسالة", original_message: "الرسالة الأصلية", analysis: "التحليل", ai_analysis: "تحليل الذكاء الاصطناعي", notes: "الملاحظات", suggested_reply: "الرد المقترح", reply_message: "الرسالة الجاهزة للرد", response_template: "قالب الرد", source: "المصدر", platform: "المنصة", detected_product: "المنتج المرصود", intent: "نية الشراء", category: "التصنيف", score: "الدرجة", final_score: "الدرجة النهائية", urgency: "الإلحاح", location_hint: "الموقع", final_contact_channel: "قناة التواصل", profile_url: "رابط الحساب", post_url: "رابط المنشور", created_at: "وقت الإنشاء", updated_at: "آخر تحديث", consent: "الموافقة", status: "الحالة", quantity: "الكمية" };
const pick = (row: Row, ...keys: string[]) => keys.map((key) => row[key]).find((value) => value?.trim()) || "";
const title = (key: string) => LABELS[key] || key.replaceAll("_", " ");
const isEmpty = (value: string) => !value || ["unknown", "null", "undefined", "false"].includes(value.toLowerCase());

function LinkButton({ href, children, icon: Icon = ExternalLink }: { href: string; children: React.ReactNode; icon?: typeof ExternalLink }) { return <a href={href} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-[#FFF7F7] px-3 py-2 text-xs font-bold text-[#C41228] border border-[#F1D9DC]"><Icon size={14} />{children}</a>; }

export default function Leads() {
  const { data, loading } = useSheets();
  const [search, setSearch] = useState("");
  const [selected, setSelected] = useState<Row | null>(null);
  const rawRows = data.rawSheets.leads || data.leads.map((lead) => lead as unknown as Row);
  const leads = useMemo(() => rawRows.filter((row) => !["true", "TRUE", "1", "yes"].includes(row.is_demo || "")).filter((row) => !search || Object.values(row).join(" ").toLowerCase().includes(search.toLowerCase())), [rawRows, search]);
  const selectedPhone = selected ? pick(selected, "phone", "mobile", "whatsapp") : "";
  const selectedReply = selected ? pick(selected, "reply_message", "suggested_reply", "response_template", "recommended_reply") : "";
  if (loading) return <DashboardLayout><div className="luxury-loading">جاري تحميل الرادار...</div></DashboardLayout>;
  return <DashboardLayout><div className="space-y-6">
    <header className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><p className="section-kicker">LEADS & CRM · RADAR</p><h1 className="text-3xl font-black">الرادار والمبيعات</h1><p className="text-sm text-muted-foreground mt-1">ملف كامل لكل عميل محتمل، مصدره، رسالته، تحليله وخطوة التواصل التالية.</p></div><div className="flex items-center gap-2 rounded-lg border border-[#E8DCC4] bg-white px-3 py-2"><Search size={15} className="text-muted-foreground" /><input className="bg-transparent text-sm outline-none" placeholder="ابحث في كل الحقول..." value={search} onChange={(event) => setSearch(event.target.value)} /></div></header>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Metric label="إجمالي السجلات" value={leads.length} /><Metric label="مع هاتف" value={leads.filter((row) => pick(row, "phone", "mobile")).length} /><Metric label="رسائل للتحليل" value={leads.filter((row) => pick(row, "message", "message_text", "original_message")).length} /><Metric label="ردود مقترحة" value={leads.filter((row) => pick(row, "reply_message", "suggested_reply", "response_template")).length} /></div>
    <div className="grid grid-cols-1 xl:grid-cols-[1.05fr_1fr] gap-5"><Card className="luxury-card"><CardContent className="p-3"><div className="max-h-[680px] overflow-auto space-y-2">{leads.map((row, index) => { const name = pick(row, "name", "full_name", "customer_name") || "عميل بلا اسم"; const message = pick(row, "message", "message_text", "original_message"); return <button key={`${pick(row, "lead_id", "id")}-${index}`} onClick={() => setSelected(row)} className={`w-full rounded-xl border p-4 text-right transition-all ${selected === row ? "border-[#C41228] bg-[#FFF8F8]" : "border-[#F0EADF] bg-white hover:border-[#E8DCC4]"}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2"><span className="font-bold text-sm truncate">{name}</span><span className="text-[10px] rounded-full bg-[#FFF8EF] px-2 py-1 text-[#8D6D32]">{pick(row, "category", "intent") || "غير مصنف"}</span></div><p className="mt-2 line-clamp-2 text-xs leading-5 text-muted-foreground">{message || "لا توجد رسالة نصية في السجل"}</p></div><div className="shrink-0 text-left"><b className="text-lg text-[#C41228]">{pick(row, "final_score", "score") || "—"}</b><small className="block text-[10px] text-muted-foreground">الدرجة</small></div></div><div className="mt-3 flex flex-wrap gap-2 text-[10px] text-muted-foreground"><span>{pick(row, "platform", "source") || "مصدر غير محدد"}</span><span>{pick(row, "location_hint", "location") || "موقع غير محدد"}</span><span>{pick(row, "created_at", "timestamp") || "وقت غير محدد"}</span></div></button>})}{!leads.length && <div className="p-14 text-center text-sm text-muted-foreground">لا توجد سجلات فعلية متاحة من الشيت.</div>}</div></CardContent></Card>
      <Card className="luxury-card"><CardContent className="p-6">{selected ? <div className="space-y-5"><div className="flex items-start justify-between"><div><p className="section-kicker">ملف العميل الكامل</p><h2 className="text-2xl font-black">{pick(selected, "name", "full_name", "customer_name") || "عميل بلا اسم"}</h2><p className="text-xs text-muted-foreground mt-1">{pick(selected, "lead_id", "id") || "بدون معرف"}</p></div><UserRound className="text-[#B38E46]" /></div><div className="flex flex-wrap gap-2">{selectedPhone && <><LinkButton href={`https://wa.me/${selectedPhone.replace(/\D/g, "")}`} icon={MessageCircle}>فتح واتساب</LinkButton><LinkButton href={`tel:${selectedPhone}`} icon={Phone}>اتصال {selectedPhone}</LinkButton></>}{pick(selected, "profile_url", "post_url", "source_url") && <LinkButton href={pick(selected, "profile_url", "post_url", "source_url")}>الحساب / المنشور</LinkButton>}</div><DetailBox icon={Activity} title="الرسالة الأصلية" value={pick(selected, "message", "message_text", "original_message")} empty="لا يوجد نص رسالة في هذا السجل." /><DetailBox icon={Activity} title="التحليل" value={pick(selected, "analysis", "ai_analysis", "notes", "intent") } empty="لا يوجد تحليل مسجل." /><DetailBox icon={Send} title="الرسالة المقترحة للرد" value={selectedReply} empty="لا يوجد رد مقترح مسجل." copy={selectedReply} /><div className="grid grid-cols-1 sm:grid-cols-2 gap-x-5 gap-y-2 border-t border-[#F0EADF] pt-4">{Object.entries(selected).filter(([key, value]) => !isEmpty(value) && !["message", "message_text", "original_message", "analysis", "ai_analysis", "notes", "reply_message", "suggested_reply", "response_template"].includes(key)).map(([key, value]) => <div key={key} className="flex justify-between gap-3 border-b border-[#F5F2ED] py-2 text-xs"><span className="text-muted-foreground">{title(key)}</span><span className="max-w-[65%] break-words text-left font-semibold">{value}</span></div>)}</div></div> : <div className="flex min-h-[520px] flex-col items-center justify-center text-center text-muted-foreground"><UserRound size={38} className="mb-3 text-[#E8DCC4]" /><p className="text-sm">اختر عميلاً لرؤية كل البيانات التشغيلية.</p></div>}</CardContent></Card></div>
  </div></DashboardLayout>;
}
function Metric({ label, value }: { label: string; value: number }) { return <Card className="luxury-card"><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><b className="mt-1 block text-2xl text-[#C41228]">{value.toLocaleString("ar-SA")}</b></CardContent></Card>; }
function DetailBox({ icon: Icon, title: heading, value, empty, copy }: { icon: typeof Activity; title: string; value: string; empty: string; copy?: string }) { return <div className="rounded-xl border border-[#E8DCC4] bg-[#FFFCF7] p-4"><div className="mb-2 flex items-center justify-between"><p className="flex items-center gap-2 text-xs font-bold text-[#8D6D32]"><Icon size={14} />{heading}</p>{copy && <button onClick={() => navigator.clipboard?.writeText(copy)} className="text-[#B38E46]" title="نسخ"><Copy size={14} /></button>}</div><p className="whitespace-pre-wrap text-sm leading-7">{value || <span className="text-muted-foreground">{empty}</span>}</p></div>; }
